spring:
  application:
    name: SimCardActivation

  datasource:
    url: jdbc:postgresql://localhost:5432/card_activation_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

  ai:
    openai:
      api-key: your_openai_api_key_here
      chat:
        options:
          model: gpt-4o-mini

server:
  port: 8081

resilience4j:
  circuitbreaker:
    instances:
      ocrService:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3

logging:
  level:
    io.github.resilience4j: INFO
    
  security:
    user:
      name: admin
      password: "{noop}admin123"

debug: true
