spring:
  application:
    name: document-verification-service

  datasource:
    url: jdbc:postgresql://localhost:5432/document_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8082

openrouter:
  api:
    key: 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



debug: true
