spring.application.name=quantumisim
# Enable multipart (file upload) processing
spring.servlet.multipart.enabled=true

# Set the maximum size for a single file (e.g., 10 Megabytes)
spring.servlet.multipart.max-file-size=10MB

# Set the maximum size for the entire request (including files and other data)
spring.servlet.multipart.max-request-size=10MB