spring:
  application:
    name: document-verification-service

  datasource:
    url: jdbc:postgresql://localhost:5432/document_verification_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 10MB

openrouter:
  api-key: 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

resilience4j.circuitbreaker:
  instances:
    ocrService:
      registerHealthIndicator: true
      slidingWindowSize: 5
      minimumNumberOfCalls: 3
      permittedNumberOfCallsInHalfOpenState: 2
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
    manualService:
      registerHealthIndicator: true
      slidingWindowSize: 5
      minimumNumberOfCalls: 3
      permittedNumberOfCallsInHalfOpenState: 2
      waitDurationInOpenState: 10s
      failureRateThreshold: 50


debug: true