spring:
  application:
    name: document-verification-service

  datasource:
    url: jdbc:postgresql://localhost:5432/document_verification_db
    username: postgres
    password: Postsid@1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 10MB

openrouter:
  api-key: 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

debug: true